
package com.training;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WeatherServiceService", targetNamespace = "http://services.training.com/", wsdlLocation = "http://localhost:5050/weather?wsdl")
public class WeatherServiceImplService
    extends Service
{

    private final static URL WEATHERSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException WEATHERSERVICESERVICE_EXCEPTION;
    private final static QName WEATHERSERVICESERVICE_QNAME = new QName("http://services.training.com/", "WeatherServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:5050/weather?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEATHERSERVICESERVICE_WSDL_LOCATION = url;
        WEATHERSERVICESERVICE_EXCEPTION = e;
    }

    public WeatherServiceImplService() {
        super(__getWsdlLocation(), WEATHERSERVICESERVICE_QNAME);
    }

    public WeatherServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEATHERSERVICESERVICE_QNAME, features);
    }

    public WeatherServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, WEATHERSERVICESERVICE_QNAME);
    }

    public WeatherServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEATHERSERVICESERVICE_QNAME, features);
    }

    public WeatherServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WeatherServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WeatherServices
     */
    @WebEndpoint(name = "WeatherServicePort")
    public WeatherServices getWeatherServicePort() {
        return super.getPort(new QName("http://services.training.com/", "WeatherServicePort"), WeatherServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WeatherServices
     */
    @WebEndpoint(name = "WeatherServicePort")
    public WeatherServices getWeatherServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.training.com/", "WeatherServicePort"), WeatherServices.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEATHERSERVICESERVICE_EXCEPTION!= null) {
            throw WEATHERSERVICESERVICE_EXCEPTION;
        }
        return WEATHERSERVICESERVICE_WSDL_LOCATION;
    }

}
