server:
  port: 7075
spring:  application:    name: book-client  
eureka:  client:    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka 